[package]
name = "melon"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
pumpkin-plugin-api = { git = "https://github.com/Pumpkin-MC/Pumpkin", tag = "0.2.0+26.3-26.51" }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[profile.release]
lto = true